version: '2'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
